# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-12 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish', '0002_aquarium_fish_fishdetection'),
    ]

    operations = [
        migrations.AddField(
            model_name='fish',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
