# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-01 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish', '0003_fish_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='aquarium',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
