# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-01 21:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fish', '0004_aquarium_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='fishdetection',
            name='aquarium_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='detections', to='fish.Aquarium'),
            preserve_default=False,
        ),
    ]
