# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-02 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish', '0005_fishdetection_aquarium_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='fishdetection',
            name='duration',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fishdetection',
            name='nb_detection',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
