# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-02 08:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish', '0006_auto_20170802_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fishdetection',
            name='nb_detection',
            field=models.FloatField(),
        ),
    ]
